export { createClient, type ClientOptions } from './client.js'
export { fetchAdapter, type Adapter, type AdapterRequest, type AdapterResponse } from './adapter.js'
export type {
  AliasCallers,
  ArgsTuple,
  MethodCallers,
  RequestArgs,
  ValidateMode,
  ZodapiClient,
} from './types.js'
export {
  ApiError,
  type ApiErrorOf,
  type DecodableResponse,
  type ErrorDecoder,
  type KeyCasing,
  PROBLEM_JSON_CONTENT_TYPE,
  ProblemApiError,
  ProblemDetails,
  type ProblemDetailsOptions,
  type ProblemFlavor,
  RequestValidationError,
  ResponseValidationError,
  UnexpectedResponseApiError,
  ValidationApiError,
  ValidationError,
  ZODAPI_VALIDATION_TYPE,
  decodeError,
  decodersFor,
  isAxiosErrorFromRoute,
  isErrorFromAlias,
  isErrorFromRoute,
  isValidationError,
  isValidationErrorBody,
  matchErrorByStatus,
  mediaTypeOf,
  problemDetails,
  zodapiValidationDecoder,
} from '@zodapi/core'
