// Generated by @zodapi/codegen. Do not edit.
import type { RouteDef } from '@zodapi/core'
import { queryArray } from '@zodapi/core'
import { z } from 'zod'
type GeneratedRoute = RouteDef & {
  operationId?: string
  summary?: string
  description?: string
  tags?: readonly string[]
}

export const isoDatetimeToDate = z.codec(z.iso.datetime(), z.date(), {
  decode: (value) => new Date(value),
  encode: (date) => date.toISOString(),
})

export const isoDateToDate = z.codec(z.iso.date(), z.date(), {
  decode: (value) => new Date(`${value}T00:00:00Z`),
  encode: (date) => date.toISOString().slice(0, 10),
})

export const Role = z.enum(["admin", "member", "guest"]).meta({ id: "Role" })
export type Role = z.infer<typeof Role>

export const User = z.object({
  id: z.uuid(),
  email: z.email(),
  name: z.string().min(1).max(100),
  age: z.int().min(0).max(150).optional(),
  score: z.number().gt(0).lt(1),
  bio: z.string().nullable(),
  role: Role,
  website: z.url().optional(),
  createdAt: isoDatetimeToDate,
  birthDate: isoDateToDate.optional(),
  tags: z.array(z.string()).min(1).max(10),
}).meta({ id: "User", description: "A registered user" })
export type User = z.infer<typeof User>

export const ValidationError = z.looseObject({
  type: z.enum(["urn:zodapi:validation"]),
  status: z.literal(400),
  target: z.enum(["json", "form", "query", "param", "header", "cookie"]),
  issues: z.array(z.looseObject({
    code: z.string(),
    path: z.array(z.union([z.string(), z.number()])),
    message: z.string(),
  })),
}).meta({ id: "ValidationError" })
export type ValidationError = z.infer<typeof ValidationError>

export const NotFound = z.object({
  error: z.object({
    code: z.enum(["NOT_FOUND"]),
    message: z.string(),
  }),
}).meta({ id: "NotFound" })
export type NotFound = z.infer<typeof NotFound>

export const Labels = z.record(z.string(), z.string()).meta({ id: "Labels" })
export type Labels = z.infer<typeof Labels>

export const Category = z.object({
  name: z.string(),
  get children() {
    return z.array(Category)
  },
}).meta({ id: "Category" })
export type Category = z.infer<typeof Category>

export const Widget = z.object({
  kind: z.enum(["widget"]),
  size: z.number(),
}).meta({ id: "Widget" })
export type Widget = z.infer<typeof Widget>

export const Gadget = z.object({
  kind: z.enum(["gadget"]),
  color: z.string(),
}).meta({ id: "Gadget" })
export type Gadget = z.infer<typeof Gadget>

export const Product = z.union([Widget, Gadget]).meta({ id: "Product" })
export type Product = z.infer<typeof Product>

export const UserCreated = z.object({
  type: z.enum(["user.created"]),
  user: User,
}).meta({ id: "UserCreated" })
export type UserCreated = z.infer<typeof UserCreated>

export const UserDeleted = z.object({
  type: z.enum(["user.deleted"]),
  userId: z.uuid(),
}).meta({ id: "UserDeleted" })
export type UserDeleted = z.infer<typeof UserDeleted>

export const Event = z.discriminatedUnion("type", [UserCreated, UserDeleted]).meta({ id: "Event" })
export type Event = z.infer<typeof Event>

export const Timestamps = z.object({
  createdAt: isoDatetimeToDate,
  updatedAt: isoDatetimeToDate,
}).meta({ id: "Timestamps" })
export type Timestamps = z.infer<typeof Timestamps>

export const AuditedNote = z.intersection(z.object({
  text: z.string(),
}), Timestamps).meta({ id: "AuditedNote" })
export type AuditedNote = z.infer<typeof AuditedNote>

export const getUser = {
  method: "get",
  path: "/users/{id}",
  alias: "getUser",
  operationId: "getUser",
  summary: "Fetch one user",
  tags: ["users"],
  request: {
    params: z.object({
      id: z.uuid(),
    }),
    headers: z.object({
      "x-request-id": z.string().optional(),
    }),
  },
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: User,
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
    404: {
      description: "missing",
      content: {
        "application/json": {
          schema: NotFound,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const deleteUsersId = {
  method: "delete",
  path: "/users/{id}",
  request: {
    params: z.object({
      id: z.uuid(),
    }),
    cookies: z.object({
      session: z.string(),
    }),
  },
  responses: {
    204: {
      description: "deleted",
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const listUsers = {
  method: "get",
  path: "/users",
  alias: "listUsers",
  operationId: "listUsers",
  request: {
    query: z.object({
      limit: z.int().min(1).max(100).default(20).optional(),
      role: Role.optional(),
      tags: queryArray(z.string()).optional(),
      search: z.string().meta({ description: "Free-text filter" }).optional(),
      since: isoDatetimeToDate.optional(),
    }),
  },
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: z.object({
            items: z.array(User),
            total: z.int(),
            labels: Labels.optional(),
          }),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const postUsers = {
  method: "post",
  path: "/users",
  request: {
    body: {
      description: "The user to create",
      content: {
        "application/json": {
          schema: z.object({
            email: z.email(),
            name: z.string(),
            remindAt: isoDatetimeToDate.optional(),
            role: Role.optional(),
            settings: z.looseObject({
              theme: z.string(),
            }).optional(),
          }),
        },
      },
      required: true,
    },
  },
  responses: {
    201: {
      description: "created",
      content: {
        "application/json": {
          schema: User,
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
    409: {
      description: "conflict",
      content: {
        "application/json": {
          schema: z.object({
            error: z.object({
              code: z.enum(["CONFLICT"]),
            }),
          }),
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const getCategories = {
  method: "get",
  path: "/categories",
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: z.array(Category),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const getProducts = {
  method: "get",
  path: "/products",
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: z.array(Product),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const getEvents = {
  method: "get",
  path: "/events",
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: z.array(Event),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const getReportsYearExport = {
  method: "get",
  path: "/reports/{year}/export",
  request: {
    params: z.object({
      year: z.int().nullable(),
    }),
  },
  responses: {
    200: {
      description: "report in the negotiated format",
      content: {
        "application/json": {
          schema: z.object({
            rows: z.array(z.tuple([z.string(), z.number(), z.boolean()])),
            matrix: z.array(z.array(z.number())),
            blob: z.unknown().optional(),
          }),
        },
        "text/csv": {
          schema: z.string(),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const getNotes = {
  method: "get",
  path: "/notes",
  alias: "getNotes",
  operationId: "getNotes",
  responses: {
    200: {
      description: "ok",
      content: {
        "application/json": {
          schema: z.array(AuditedNote),
        },
      },
    },
    400: {
      description: "Request validation failed",
      content: {
        "application/problem+json": {
          schema: ValidationError,
        },
      },
    },
  },
} as const satisfies GeneratedRoute

export const routes = [
  getUser,
  deleteUsersId,
  listUsers,
  postUsers,
  getCategories,
  getProducts,
  getEvents,
  getReportsYearExport,
  getNotes,
] as const

export const problemFlavor: 'zodapi' | 'problem-details' | undefined = "zodapi"
