// Generated by @zodapi/codegen. Do not edit.
import { route, wireBoolean, wireNumber } from '@zodapi/core'
import { z } from 'zod'
export const getItem = route({
  method: 'get',
  path: '/items/{id}',
  alias: 'getItem',
  operationId: 'getItem',
  request: {
    params: z.object({
      id: wireNumber(z.int().min(1)),
    }),
    query: z.object({
      verbose: wireBoolean(z.boolean()).optional(),
      ratio: wireNumber(z.number().min(0).max(1)).optional(),
    }),
  },
  responses: {
    200: {
      description: 'ok',
      content: {
        'application/json': {
          schema: z.object({
            id: z.int().optional(),
          }),
        },
      },
    },
  },
})

export const listItems = route({
  method: 'get',
  path: '/items',
  alias: 'listItems',
  operationId: 'listItems',
  responses: {
    200: {
      description: 'ok',
    },
    400: {
      description: 'the backend’s own bad request',
      content: {
        'application/json': {
          schema: z.object({
            message: z.string().optional(),
          }),
        },
      },
    },
  },
})

export const routes = [getItem, listItems] as const

export const problemFlavor: 'zodapi' | 'problem-details' | undefined = undefined
